<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MarketData.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Protos\orderbook.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.3" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Net.Client" Version="2.65.0" />
    <PackageReference Include="Grpc.Tools" Version="2.65.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Protos\" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos\orderbook.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
